remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Default:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

anthonykgrossfr_main_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

anthonykgrossfr_contactez_moi:
    path:     /contact
    defaults: { _controller: AppBundle:Default:sendmail }
    
anthonykgrossfr_cv:
    path:     /cv
    defaults: { _controller: AppBundle:Default:cv }
    
anthonykgrossfr_captcha:
    path:     /captcha
    defaults: { _controller: AppBundle:Default:captcha }
    
anthonykgrossfr_blog:
    path:     /blog
    defaults: { _controller: AppBundle:Page:blog }
    
anthonykgrossfr_event:
    path:     /evenements
    defaults: { _controller: AppBundle:Page:event }

anthonykgrossfr_event2:
    path:     /event
    defaults: { _controller: AppBundle:Default:event }
    
anthonykgrossfr_project:
    path:     /projets
    defaults: { _controller: AppBundle:Page:project }

anthonykgrossfr_project2:
    path:     /project
    defaults: { _controller: AppBundle:Default:project }
    
anthonykgrossfr_page_lire:
    path:     /p/{name}
    defaults: { _controller: AppBundle:Page:lire }